### ISSUE TITLE
why cutadapt 1.1.2?

### ISSUE THREAD

**Issue by dy7t** [Sethupathy-Lab/miRquant#1]
The directions says miRquant needs cutadapt version 1.1.2.  But, no such version is shown at https://github.com/marcelm/cutadapt/releases

**Comment by dy7t** [comment]
I see now the requirements.txt file contains "cutadapt==1.12" so I presume README.md file that says cutadapt version 1.1.2 are mistakes and should say version 1.12

**Comment by Sethupathy-Lab** [comment]
The correct version is 1.12.  I've updated the README.md file. Thanks for bringing it to my attention.
